//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppEF1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassesTBL
    {
        public int ClassID { get; set; }
        public string ClassName { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
